In [1]:
import sys
from pathlib import Path

# Asumsikan kamu menjalankan notebook dari 'data_pipeline_pyspark/notebooks'
# dan kamu ingin import dari 'data_pipeline_pyspark/src'
project_root = Path.cwd().parent
sys.path.append(str(project_root))


from src.staging.extract.extract_db import extract_database
from src.staging.extract.extract_spreadsheet import extract_spreadsheet
from src.staging.extract.extract_api import extract_api_milestones
from src.staging.load.load import load_staging
from src.staging.extract.extract_spreadsheet import extract_spreadsheet, extract_sheet

# Staging

## Extract

### api

In [5]:
df_staging_api = extract_api_milestones(table_name='milestones')
df_staging_api

Empty DataFrame
Columns: []
Index: []

### spreadsheet

In [5]:
# relationship 
people_df = extract_spreadsheet(table_name='people')
people_df

# people 
relationships_df = extract_spreadsheet(table_name='relationships')
relationships_df

babai
babai

,relationship_id,person_object_id,relationship_object_id,start_at,end_at,is_past,sequence,title,created_at,updated_at
1,1,p:2,c:1,NaN,NaN,FALSE,8,Co-Founder/CEO/Board of Directors,2007-05-25 07:03:54.000,2013-06-03 09:58:46.000
2,2,p:3,c:1,NaN,NaN,FALSE,279242,VP Marketing,2007-05-25 07:04:16.000,2010-05-21 16:31:34.000
3,3,p:4,c:3,NaN,NaN,FALSE,4,Evangelist,2007-05-25 19:33:03.000,2013-06-29 13:36:58.000
4,4,p:5,c:3,2006-03-01 00:00:00.000,2009-12-01 00:00:00.000,FALSE,4,Senior Director Strategic Alliances,2007-05-25 19:34:53.000,2013-06-29 10:25:34.000
5,6,p:7,c:4,2005-07-01 00:00:00.000,2010-04-05 00:00:00.000,FALSE,1,Chief Executive Officer,2007-05-25 20:05:33.000,2010-04-05 18:41:41.000
...,...,...,...,...,...,...,...,...,...,...
134722,196878,p:35873,c:59431,2012-04-01 00:00:00.000,NaN,FALSE,6,Board Member,2013-02-14 17:30:02.000,2013-08-12 09:07:21.000
134723,196879,p:35873,c:151478,NaN,NaN,FALSE,8,Investor,2013-02-14 17:30:32.000,2013-08-12 09:07:21.000
134724,196881,p:4345,c:187489,2012-08-01 00:00:00.000,NaN,FALSE,306113,President,2013-02-14 17:33:44.000,2013-02-14 20:39:26.000
134725,196886,p:137337,c:187489,2012-09-15 00:00:00.000,NaN,FALSE,2,Chief Financial Officer,2013-02-14 17:36:01.000,2013-02-14 20:39:36.000
134726,196888,p:452,c:12007,2013-02-11 00:00:00.000,NaN,FALSE,20,Board Director,2013-02-14 17:36:56.000,2013-07-07 10:02:54.000

In [10]:
# relationship 
people_df = extract_spreadsheet(table_name='people')
people_df

# people 
relationships_df = extract_spreadsheet(table_name='relationships')
relationships_df

babai
babai

,relationship_id,person_object_id,relationship_object_id,start_at,end_at,is_past,sequence,title,created_at,updated_at
1,1,p:2,c:1,NaN,NaN,FALSE,8,Co-Founder/CEO/Board of Directors,2007-05-25 07:03:54.000,2013-06-03 09:58:46.000
2,2,p:3,c:1,NaN,NaN,FALSE,279242,VP Marketing,2007-05-25 07:04:16.000,2010-05-21 16:31:34.000
3,3,p:4,c:3,NaN,NaN,FALSE,4,Evangelist,2007-05-25 19:33:03.000,2013-06-29 13:36:58.000
4,4,p:5,c:3,2006-03-01 00:00:00.000,2009-12-01 00:00:00.000,FALSE,4,Senior Director Strategic Alliances,2007-05-25 19:34:53.000,2013-06-29 10:25:34.000
5,6,p:7,c:4,2005-07-01 00:00:00.000,2010-04-05 00:00:00.000,FALSE,1,Chief Executive Officer,2007-05-25 20:05:33.000,2010-04-05 18:41:41.000
...,...,...,...,...,...,...,...,...,...,...
134722,196878,p:35873,c:59431,2012-04-01 00:00:00.000,NaN,FALSE,6,Board Member,2013-02-14 17:30:02.000,2013-08-12 09:07:21.000
134723,196879,p:35873,c:151478,NaN,NaN,FALSE,8,Investor,2013-02-14 17:30:32.000,2013-08-12 09:07:21.000
134724,196881,p:4345,c:187489,2012-08-01 00:00:00.000,NaN,FALSE,306113,President,2013-02-14 17:33:44.000,2013-02-14 20:39:26.000
134725,196886,p:137337,c:187489,2012-09-15 00:00:00.000,NaN,FALSE,2,Chief Financial Officer,2013-02-14 17:36:01.000,2013-02-14 20:39:36.000
134726,196888,p:452,c:12007,2013-02-11 00:00:00.000,NaN,FALSE,20,Board Director,2013-02-14 17:36:56.000,2013-07-07 10:02:54.000

In [8]:
relationships_df

,relationship_id,person_object_id,relationship_object_id,start_at,end_at,is_past,sequence,title,created_at,updated_at
1,1,p:2,c:1,NaN,NaN,FALSE,8,Co-Founder/CEO/Board of Directors,2007-05-25 07:03:54.000,2013-06-03 09:58:46.000
2,2,p:3,c:1,NaN,NaN,FALSE,279242,VP Marketing,2007-05-25 07:04:16.000,2010-05-21 16:31:34.000
3,3,p:4,c:3,NaN,NaN,FALSE,4,Evangelist,2007-05-25 19:33:03.000,2013-06-29 13:36:58.000
4,4,p:5,c:3,2006-03-01 00:00:00.000,2009-12-01 00:00:00.000,FALSE,4,Senior Director Strategic Alliances,2007-05-25 19:34:53.000,2013-06-29 10:25:34.000
5,6,p:7,c:4,2005-07-01 00:00:00.000,2010-04-05 00:00:00.000,FALSE,1,Chief Executive Officer,2007-05-25 20:05:33.000,2010-04-05 18:41:41.000
...,...,...,...,...,...,...,...,...,...,...
134722,196878,p:35873,c:59431,2012-04-01 00:00:00.000,NaN,FALSE,6,Board Member,2013-02-14 17:30:02.000,2013-08-12 09:07:21.000
134723,196879,p:35873,c:151478,NaN,NaN,FALSE,8,Investor,2013-02-14 17:30:32.000,2013-08-12 09:07:21.000
134724,196881,p:4345,c:187489,2012-08-01 00:00:00.000,NaN,FALSE,306113,President,2013-02-14 17:33:44.000,2013-02-14 20:39:26.000
134725,196886,p:137337,c:187489,2012-09-15 00:00:00.000,NaN,FALSE,2,Chief Financial Officer,2013-02-14 17:36:01.000,2013-02-14 20:39:36.000
134726,196888,p:452,c:12007,2013-02-11 00:00:00.000,NaN,FALSE,20,Board Director,2013-02-14 17:36:56.000,2013-07-07 10:02:54.000

## Load

In [9]:
load_staging(data=people_df, table_name='people', schema='public', idx_name='people_id', source='spreadsheet people')
load_staging(data=relationships_df, table_name='relationships', schema='public', idx_name='relationship_id', source='spreadsheet relationships')